import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../globals.scss';
import Nav from '@/components/nav/nav';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const logo = {};
  return (
    <html>
      <body className={inter.className}>
        <Nav
          logo={{
            src: 'https://placehold.co/10x10/ABC/31343C',
            alt: 'LOGO',
          }}
          content={[]}
        />
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
